[pytest]
addopts = -s --alluredir=./report/allure_results
testpaths = ./scripts
python_files = test*.py
python_classes = Test*
python_functions = test*
markers =
    single: 单接口测试
    scenario: 场景链路测试